### ISSUE TITLE
u dum

### ISSUE THREAD

**Issue by RoboticObsession** [GhostSlayer/DDoS-tool#3]
u are and idiot :)

**Comment by GhostSlayer** [comment]
Thanks, why bully me since u made this?? 🤔

**Comment by GhostSlayer** [comment]
Dont bully me anymore

Sent from my Samsung Fridge

**Comment by RemiixInc** [comment]
> u are and idiot :)

https://docs.github.com/en/github/site-policy/github-community-guidelines#hate-speech-and-discrimination
> level of experience

**Comment by Donut901** [comment]
Robotic Unobsession has joined the chat

**Comment by RiversideRocks** [comment]
Life

**Comment by RoboticObsession** [comment]
Sorry for saying this :(

**Comment by GhostSlayer** [comment]
yes

**Comment by GhostSlayer** [comment]
> Sorry for saying this :(

i dont allow
