### ISSUE TITLE
dos tol no wokrei!!!!!!!!

### ISSUE THREAD

**Issue by aquaticdosDev** [GhostSlayer/DDoS-tool#7]
i wnt dos me fienr ot nro wrok!!!!!!!!

**Comment by sinmineryt** [comment]
yes it no work i wnated to hack gogel :(((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((((( PELaeE WORK I GIVE YOU VBOVCKS!121!1!! 😎😎😎😎😎😎😎😎😪😪😪😪😪😪😪😪😪😪😪😫😫😫😫😫😫😫😫🥱🥱😴😴😴😴😴😴😴😴😓😓😓😓😓😒😒😒🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤🤤

**Comment by aquaticdosDev** [comment]
nrvrmed i has to prezz "nodz indzr.jz"

**Comment by sinmineryt** [comment]
IT STILL NO WOR K GOOGLE  WORKING LEI

**Comment by sinmineryt** [comment]
THSIJ DOS TUK L  SUX

**Comment by aquaticdosDev** [comment]
WJOT
IT NRO WRONK???!?!?

**Comment by sinmineryt** [comment]
AUTOR PELASE FXI RO I WILL HACKET YOU WITH MY FAD BECAUSE HE AWORKS AT FBI

**Comment by aquaticdosDev** [comment]
YESZZZR
FIX TI PLISSSSSSSSSS I COMMAND YU TRO FRIXXXX

**Comment by sinmineryt** [comment]
THIS iS NOT TF AK!121!!!

**Comment by sinmineryt** [comment]
FIX NOEW 😡😡😡😡😡😡😡😠😠😠🥳🥳🥳🥳😡😡😡🤬🤬🤬😡😡😠😠😡😡🤬🤬🤬🤬😡😠😠🤬🤬🤬🤬🤬😡😡😡😡😡🤬🤬😡😠😠😠😡😡🤬🤬🤬😡😡😡😡😡🤬🤬🤬

**Comment by aquaticdosDev** [comment]
gyus hwo dio i bucome  impestor jm amngujs

**Comment by GhostSlayer** [comment]
among sus 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳 😳

**Comment by sinmineryt** [comment]
> 
> 
> gyus hwo dio i bucome impestor jm amngujs

YOU NEED TO BE SUS! 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂  (A MONG SUS RFEFERENDE!!!) 😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣😂😂😂😂😂😂😂😂🤣🤣🤣😂😂😁😁😁😂😂😂🤣🤣🤣🤣🤣🤣🤣😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by aquaticdosDev** [comment]
OGGGGGMMMMM!!!!!!1 THINK YU

**Comment by sinmineryt** [comment]
I AM SO DEPERSEED IUF YOIU NO FIX !!! ### )( : (((((((((((((((((( 😣😣😣😣😣😣😣😣😣😣😣😣😣😣😥😥😥😥😥😥😥😥😥😥😣😣😣😣😣😣😥😥😥😥😪😪😪😪😪😪😪😪😪😫😫😫😫😫😫🥱🥱🥱🥱🥱🥱🥱😫😫😫😫😫😫😫😫😪😪😪😪😪☹☹☹☹☹☹☹☹🙁🙁🙁🙁🙁🙁🙁🙁🙁🙁🙁😖😖😖😖😖😞😞😞😞😞😞😟😟😟😟😟😟😞😖😖🙁🙁🙁🙁🙁🙁☹☹☹☹🙁🙁🙁😖😖😢😢😢😢😢😢😭😭😦😦😦😭😢😢😢😢😢😢😢😢😢😢🥵🥵🥵🥵🥵😧😧😧😧😨😨😨😨😨😨😨😧😧😧😧😧😧😧😨😨😨😨😨😩😩😩😩😩😩😩🤯🤯🤯🤯🤯😟😟🩸🩸🩸🩸🩸🔪🔪🔪🔪🔪🔪🔪🔪

**Comment by aquaticdosDev** [comment]
O MMMMMGMGG, I KLII FERID IRLLLL1 :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing: :laughing:  H SWA SUS

**Comment by RiversideRocks** [comment]
SUS CONFIRMED

**Comment by sinmineryt** [comment]
![grafik](https://user-images.githubusercontent.com/50749166/108631890-7ef1d500-746c-11eb-9155-cfe81ba41860.png)

**Comment by aquaticdosDev** [comment]
### 

> [`**SUS__**`](

- 

- [ ] 1. url

)

**Comment by sinmineryt** [comment]
what the

**Comment by RiversideRocks** [comment]
Anyway what is going on here

**Comment by GhostSlayer** [comment]
> Anyway what is going on here

THIAS MESAGE IS SUS

**Comment by RiversideRocks** [comment]
@GhostSlayer is the imposter

**Comment by sinmineryt** [comment]
https://www.youtube.com/watch?v=2ocykBzWDiM WATCH THIS VIDE OFR FRERWEE BOBUX !!!"!

**Comment by aquaticdosDev** [comment]
SUS

**Comment by RiversideRocks** [comment]
Ok guys lets vote

**Comment by RiversideRocks** [comment]
I vote for slayer

**Comment by sinmineryt** [comment]
YES SEX

**Comment by sinmineryt** [comment]
SEYX BIW

**Comment by aquaticdosDev** [comment]
![image](https://user-images.githubusercontent.com/79051667/108631941-1eb36100-7475-11eb-98ab-ffe860939af4.png)
GYUS MOG FRE IMPOTRSOS

**Comment by RiversideRocks** [comment]
Ok guys slayer was ejected from the ship

**Comment by RiversideRocks** [comment]
He was the imposter

**Comment by GhostSlayer** [comment]
> I vote for slayer

0OINONHOIPNOIIOKOINOINOPN00OONPOPNOPNOPNONONO0NO0NO0ON0O0N0ONBO0NONNBNBMNBKMB+'ÅKJMÅOPJU3509Å+TYH40835TN 5I3 TG3IPTGB35R'¨0PTG42RHN58I0423JR5 0¨2'5JR324RK IOPMJR4Ä*gvä

**Comment by RiversideRocks** [comment]
WE WON!!!!!

YESESYYYES

**Comment by sinmineryt** [comment]
YES SEX MNE NOW!22"""222221!!"1w1!"2"2212" AMING US !1!22"" 🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣😂😂😂😂😂😂🤣🤣🤣🤣🤣🤣😂😁😁😁😁😂😅😅😅😃😂😂😂😄😄😄😃😊😊😘😘😎😙🤩🤩😘😘🤗🙄🙄🤩😚😐🤔🤔🥰😘😍🙂😶😐🙄🙄🤗😍😍🙄😪🤐

**Comment by aquaticdosDev** [comment]
YSEEEE111!1!11!

**Comment by aquaticdosDev** [comment]
H SUS

**Comment by sinmineryt** [comment]
G SUS

**Comment by sinmineryt** [comment]
VOTE G

**Comment by sinmineryt** [comment]
WHY ARE YOU CLOSING AND REOPENING

**Comment by aquaticdosDev** [comment]
H SUS

**Comment by aquaticdosDev** [comment]
NOOoOoOOo

**Comment by sinmineryt** [comment]
SEX

**Comment by GhostSlayer** [comment]
FIXED IN PATCH V534.SUS.336254.AMOGUS.63

**Comment by HappyDarion** [comment]
SUS LIKE AMONG US

**Comment by GhostSlayer** [comment]
> SEX

{
  "content": "this `supports` __a__ **subset** *of* ~~markdown~~ 😃 ```js\nfunction foo(bar) {\n  console.log(bar);\n}\n\nfoo(1);```",
  "embed": {
    "title": "title ~~(did you know you can have markdown here too?)~~",
    "description": "this supports [named links](https://discordapp.com) on top of the previously shown subset of markdown. ```\nyes, even code blocks```",
    "url": "https://discordapp.com",
    "color": 679984,
    "timestamp": "2021-02-21T16:37:59.957Z",
    "footer": {
      "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png",
      "text": "footer text"
    },
    "thumbnail": {
      "url": "https://cdn.discordapp.com/embed/avatars/0.png"
    },
    "image": {
      "url": "https://cdn.discordapp.com/embed/avatars/0.png"
    },
    "author": {
      "name": "author name",
      "url": "https://discordapp.com",
      "icon_url": "https://cdn.discordapp.com/embed/avatars/0.png"
    },
    "fields": [
      {
        "name": "🤔",
        "value": "some of these properties have certain limits..."
      },
      {
        "name": "😱",
        "value": "try exceeding some of them!"
      },
      {
        "name": "🙄",
        "value": "an informative error should show up, and this view will remain as-is until all issues are fixed"
      },
      {
        "name": "<:thonkang:219069250692841473>",
        "value": "these last two",
        "inline": true
      },
      {
        "name": "<:thonkang:219069250692841473>",
        "value": "are inline fields",
        "inline": true
      }
    ]
  }
}

**Comment by aquaticdosDev** [comment]
> FIXED IN PATCH V534.SUS.336254.AMOGUS.63

nYOT FIX

**Comment by aquaticdosDev** [comment]
I NRO WROK

**Comment by HappyDarion** [comment]
what is that that doesnt seem very among us sus

**Comment by HappyDarion** [comment]
AQUA YU NIID TU WRKO

**Comment by aquaticdosDev** [comment]
O MG G GMGMG
DAROINN

**Comment by aquaticdosDev** [comment]
(dont question me lmao)

**Comment by HappyDarion** [comment]
GOU TTU WRKO

**Comment by HappyDarion** [comment]
YEEYEYEYEYS

**Comment by aquaticdosDev** [comment]
NOYOYOYOY

**Comment by GhostSlayer** [comment]
what the hell again

**Comment by HappyDarion** [comment]
GOU NAUW !!!!!111@!!!!

**Comment by GhostSlayer** [comment]
no agane

**Comment by GhostSlayer** [comment]
my issue now haha

**Comment by HappyDarion** [comment]
I CAN SPEAK AGAIN

**Comment by sinmineryt** [comment]
FUC KYOU

**Comment by sinmineryt** [comment]
SO PENIS

**Comment by HappyDarion** [comment]
HEELLO IM BACLO

**Comment by HappyDarion** [comment]
BACK

**Comment by Cuurle** [comment]
HELO KAN I JOYN

**Comment by sinmineryt** [comment]
no

**Comment by Cuurle** [comment]
me sad :(

**Comment by sinmineryt** [comment]
ok

**Comment by sinmineryt** [comment]
I want to sex aqua.

**Comment by sinmineryt** [comment]
@aquaticdosDev sex me now

**Comment by aquaticdosDev** [comment]
IT STRIL NRO WROK!!!!!!
I STRIL WRANT DDOIS FRIEND

**Comment by sinmineryt** [comment]
I FOUND BETTER TOTURIAL HOW TO DODS11!

**Comment by sinmineryt** [comment]
@aquaticdosDev
